version: "3.3"

services:
  django_db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: order_app
    volumes:
      - /root/pg_db:/var/lib/postgresql/data
    networks:
      - app-network

  proxy:
    depends_on:
      - django_app
      - rails_front
    image: valdrinkuchi/proxy
    volumes:
      - /etc/letsencrypt/archive/valdrinkuchi.com-0001:/ssl
      - static_data:/vol/static
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    networks:
      - app-network

  django_app:
    depends_on:
      - django_db
    environment:
      DB_HOST: django_db
    image: valdrinkuchi/order_app:latest
    volumes:
      - static_data:/vol/web
    networks:
      - app-network

  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: portfolio
    volumes:
      - /rails/pg_db:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    volumes:
      - /redis-data:/var/lib/redis
    networks:
      - app-network

  rails_back:
    image: valdrinkuchi/portfolio_backend:latest
    volumes:
      - ./master.key:/config/master.key
      - ./application.yml:/config/application.yml
    depends_on:
      - db
      - redis
    networks:
      - app-network
  rails_front:
    image: valdrinkuchi/portfolio_frontend:latest
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  static_data:
  media_data:
