version: "3.3"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: portfolio
    ports:
      - "5433:5432"
    networks:
      - app-network

  redis:
    image: redis:alpine
    environment:
      REDIS_URL: "redis://redis:6379/0/cache"
    # ports:
    #   - "6379:6379"
    networks:
      - app-network
  rails_back:
    image: valdrinkuchi/portfolio_backend
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
