development:
  adapter: postgresql
  encoding: unicode
  database: portfolio
  host: db
  posrt: 5432
  pool: 5
  username: postgres
  password: 123456

# development:
#   adapter: postgresql
#   encoding: unicode
#   database: portfolio
#   host: localhost
#   pool: 5
#   username: postgres
#   password:

production:
  adapter: postgresql
  encoding: unicode
  database: portfolio
  host: db
  posrt: 5432
  pool: 5
  username: postgres
  password: 123456
