version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    labels:
      - "dependencies"
      - "ruby"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: Europe/Berlin
    labels:
      - "dependencies"
      - "gh-action"
